# *************
# Configuration
# *************

# Rule identifiers to exclude from running
disabled_rules:
- trailing_whitespace

# Rules disabled by default we want to enable
opt_in_rules:
- empty_count
- empty_string

# Paths to ignore during linting.
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

# *****
# Lines
# *****

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

# *********
# Functions
# *********

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

# *****
# Files
# *****

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

# ****
# Misc
# ****

cyclomatic_complexity:
    warning: 15
    error: 25

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
reporter: "xcode"
